trigger:
  - main

pool:
  vmImage: 'windows-latest'

variables:
  nodeVersion: '22.x'
  #allure_results: 'allure-results'
  #allure_report: 'allure-report'

steps:
  # Install Node.js
  - task: UseNode@1
    inputs:
      version: $(nodeVersion)
    displayName: 'Install Node.js'

  # Install dependencies
  - script: |
      npx playwright install --with-deps
      npm ci
    displayName: 'Install dependencies and playwright browsers'

  # # Build the project
  # - script: |
  #     npx playwright install
  #   displayName: 'Install Playwright Browsers'

  # Run tests
  - script: |
      npm run ecommerceTestRegression
    displayName: 'Run playwright tests'
    continueOnError: true

  - script: |
      npm run report
    displayName: 'Generate Cucumber HTML Report'
    condition: always()

  # # Copy project files to artifact staging directory
  # - task: CopyFiles@2
  #   inputs:
  #     sourceFolder: '$(Build.SourcesDirectory)'
  #     contents: |
  #       src/**
  #       public/**
  #     targetFolder: '$(Build.ArtifactStagingDirectory)'
  #   displayName: 'Copy project files'

  # - task: PublishBuildArtifacts@1
  #   inputs:
  #     PathtoPublish: '$(allure_report)'
  #     ArtifactName: 'AllureReport'
  #   displayName: 'Publish Allure Report Artifact'
  # Publish pipeline artifact
  - task: PublishBuildArtifacts@1
    inputs:
      PathtoPublish: 'reports'
      ArtifactName: 'CucumberReports'
      publishLocation: 'Container'
    displayName: 'Publish Cucumber Reports'
    condition: always()

    -script: |
      echo "Mark Pipeline Failed"
      exit 1
    displayName: 'Marked the pipeline failed'
    condition: failed()